import {createInitialGame,dealHand,publicView,legalCards,playCard,finalizeHand,SUIT_SYMBOLS,HAND_TYPES,applyBid,nextPlayer,conversionPoints} from './core.js';
import {chooseCard,chooseBid,chooseContract} from './bot.js';
const $=s=>document.querySelector(s), app=$('#app');
const makeId=()=>globalThis.crypto?.randomUUID?globalThis.crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)});
let clientId=localStorage.clientId||makeId();localStorage.clientId=clientId;let role=localStorage.role||null, nickname=localStorage.nickname||'', position=Number(localStorage.position||0), session=null, game=null, selected=null, selectedAuction=null, timer=null, seconds=30, lobbyTimer=null;
const BOTN=['Bot1','Bot2','Bot3'];
const save=()=>{if(role==='master'&&game){localStorage.activeKing=JSON.stringify({savedAt:Date.now(),game,session});}};
const api=async(path,data)=>{const r=await fetch(path,{method:data?'POST':'GET',headers:{'content-type':'application/json'},body:data?JSON.stringify(data):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||'Erro');return j};
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function home(){clearInterval(timer);app.innerHTML=`<div class="shell"><div class="panel home stack"><h1>KING</h1><div>Regulamento Nacional · 4 jogadores</div><label>Nickname<input id="nick" maxlength="20" value="${nickname}"></label><div class="row"><button class="btn primary" id="create">Criar partida</button><button class="btn secondary" id="join">Entrar na partida</button><button class="btn secondary" id="offline">Jogar offline</button></div><button class="btn secondary" id="hist">Histórico</button><div id="status" class="muted"></div></div></div>`;$('#create').onclick=createLobby;$('#join').onclick=joinLobby;$('#offline').onclick=startOffline;$('#hist').onclick=showHistory;api('/api/status').then(s=>{$('#status').textContent=s.session?`Partida: ${s.session.status}`:'Sem partida online ativa'}).catch(()=>{$('#status').textContent='Servidor indisponível — modo offline disponível'});}
function getNick(){nickname=$('#nick').value.trim();if(!nickname)throw new Error('Indique um nickname');localStorage.nickname=nickname;return nickname}
async function createLobby(){try{getNick();const r=await api('/api/session/create',{clientId,nickname});role='master';position=0;session=r.session;localStorage.role=role;localStorage.position=0;listen();renderLobby();let left=30;clearInterval(lobbyTimer);lobbyTimer=setInterval(async()=>{left--;const x=$('#left');if(x)x.textContent=left;if(left<=0){clearInterval(lobbyTimer);await startOnlineMaster();}},1000)}catch(e){toast(e.message)}}
async function joinLobby(){try{getNick();const st=await api('/api/status');if(!st.session){toast('Não existe partida disponível');return}if(st.session.status!=='LOBBY'){renderWaiting();return}const r=await api('/api/session/join',{clientId,nickname});role='client';position=r.position;session=r.session;localStorage.role=role;localStorage.position=position;listen();renderLobby()}catch(e){toast(e.message)}}
function listen(){const es=new EventSource('/api/events?clientId='+clientId);es.addEventListener('session',e=>{session=JSON.parse(e.data);if(session?.status==='ACTIVE'&&role==='client')renderClientWaiting();else if(session?.status==='SUSPENDED')renderSuspended();else if(session?.status==='COMPLETED'||session?.status==='INCOMPLETE')home();else if(session?.status==='LOBBY')renderLobby()});es.addEventListener('join',e=>{if(role==='master'){const p=JSON.parse(e.data);session.players.push(p);renderLobby()}});es.addEventListener('state',e=>{if(role==='client'){game=JSON.parse(e.data).view;renderGame()}});es.addEventListener('action',e=>{if(role==='master')handleRemote(JSON.parse(e.data))});}
function renderLobby(){app.innerHTML=`<div class="shell"><div class="panel home stack"><h2>A formar mesa</h2><div>Início em <b id="left">30</b> s</div>${(session?.players||[]).map(p=>`<div>${p.position+1}. ${p.nickname}${p.master?' (master)':''}</div>`).join('')}<div class="muted">Os lugares livres serão preenchidos por bots.</div></div></div>`}
async function startOnlineMaster(){const humans=session.players.slice();const used=new Set(humans.map(p=>p.position));let bi=0;for(let p=0;p<4;p++)if(!used.has(p))humans.push({id:'bot-'+(bi+1),nickname:BOTN[bi++],position:p,bot:true});humans.sort((a,b)=>a.position-b.position);game=createInitialGame(humans);dealHand(game);await api('/api/session/start',{clientId});save();await pushViews();renderGame();runTurn()}
function startOffline(){try{getNick();role='master';position=0;session={offline:true,players:[]};game=createInitialGame([{id:clientId,nickname,bot:false},{id:'bot-1',nickname:'Bot1',bot:true},{id:'bot-2',nickname:'Bot2',bot:true},{id:'bot-3',nickname:'Bot3',bot:true}]);dealHand(game);save();renderGame();runTurn()}catch(e){toast(e.message)}}
async function pushViews(){if(session?.offline||!game)return;const views={};for(const p of game.players)if(!p.bot)views[p.id]=publicView(game,p.position);try{await api('/api/state',{clientId,views})}catch{}}
function cardHTML(c,i,legal=true){if(!c)return `<div class="card back"></div>`;const red=c.suit==='H'||c.suit==='D';return `<button class="card ${red?'red':''} ${!legal?'disabled':''} ${selected===c.id?'selected':''}" data-card="${c.id}" ${!legal?'disabled':''}><span>${c.rank}</span><span>${SUIT_SYMBOLS[c.suit]}</span></button>`}
function handLabel(){return game.handType.replaceAll('_',' ')}
function trickHTML(){const plays=game.tableTrick?.length?game.tableTrick:game.currentTrick||[];const relPos=new Map([[position,'bottom'],[(position+1)%4,'left'],[(position+2)%4,'top'],[(position+3)%4,'right']]);return `<div class="trick-board">${plays.map(x=>`<div class="played-card ${relPos.get(x.player)||''}"><div class="played-by">${game.players[x.player]?.nickname||''}</div>${cardHTML(x.card)}</div>`).join('')}</div>`}
function renderGame(){if(!game)return;const view=role==='client'?game:publicView(game,position);const rel=[position,(position+1)%4,(position+2)%4,(position+3)%4];const classes=['bottom','left','top','right'];const legalIds=new Set((role==='master'&&game.turn===position?legalCards(game,position):role==='client'&&game.turn===position?legalCards(game,position):[]).map(c=>c.id));app.innerHTML=`<div class="shell"><div class="toolbar"><b>${handLabel()}</b><span>•</span><span>Distribuidor: ${game.players[game.dealer]?.nickname}</span><span class="timer" id="timer">${game.turn===position?seconds:''}</span></div><div class="table"><div class="score">${game.players.map((p,i)=>`${p.nickname}: ${game.totals[i]} pts · ${game.trickCounts[i]} vazas`).join('<br>')}</div>${rel.map((p,k)=>`<div class="seat ${classes[k]} ${game.turn===p?'active':''}"><div class="name">${game.players[p].nickname}</div><div class="cards">${view.hands[p].map(c=>c?cardHTML(c,0,game.turn===p&&p===position?legalIds.has(c.id):true):cardHTML(null)).join('')}</div>${p===position&&game.turn===p&&selected?`<button class="btn secondary" id="cancelSelection">Anular</button>`:''}</div>`).join('')}<div class="center">${game.mode==='AUCTION'?auctionHTML():trickHTML()}</div></div><div class="toolbar"><button class="btn secondary" id="last">Última vaza</button><button class="btn danger" id="leave">Sair da partida</button></div></div>`;document.querySelectorAll('[data-card]').forEach(b=>{b.onclick=()=>{const id=b.dataset.card;if(selected===id){confirmPlay();return}selected=id;renderGame()}});if($('#cancelSelection'))$('#cancelSelection').onclick=()=>{selected=null;renderGame()};if($('#last'))$('#last').onclick=()=>{const t=game.wonTricks?.at(-1);toast(t?`Última vaza: ${t.cards.map(x=>x.card.id).join(' · ')} — ${game.players[t.winner].nickname}`:'Ainda não existe vaza anterior')};if($('#leave'))$('#leave').onclick=()=>home();}
function auctionHTML(){const a=game.auction;const b=game.beneficiary;const canOffer=a?.active?.includes(position)&&game.turn===position;const only=a?.active?.length<=1;let controls='';if(canOffer)controls=`<div class="row"><select id="kind"><option value="POSITIVE">Positivos</option><option value="NULL">Nulos</option></select><select id="val">${[1,2,3,4,5,6,7,8].map(v=>`<option>${v}</option>`).join('')}</select><button class="btn secondary" id="prebid">Pré-selecionar oferta</button><button class="btn secondary" id="pass">Pré-selecionar Passo</button><button class="btn primary" id="confirmBid">Confirmar</button></div>`;if(position===b&&only)controls+=`<div class="row"><button class="btn primary" id="freeContract">Escolher contrato</button><button class="btn secondary" id="fourthree">4×3×3×3</button></div>`;setTimeout(bindAuction,0);return `<div class="auction"><b>Benefício: ${game.players[b].nickname}</b><div class="history">${(a?.history||[]).map(h=>h.type==='PASS'?`${game.players[h.player].nickname}: Passo`:`${game.players[h.player].nickname}: ${h.value} ${h.kind==='NULL'?'Nulos':'Positivas'}`).join('<br>')}</div>${controls}</div>`}
function bindAuction(){if($('#prebid'))$('#prebid').onclick=()=>{selectedAuction={type:'BID',kind:$('#kind').value,value:Number($('#val').value)};toast('Oferta pré-selecionada')};if($('#pass'))$('#pass').onclick=()=>{selectedAuction={type:'PASS'};toast('Passo pré-selecionado')};if($('#confirmBid'))$('#confirmBid').onclick=confirmAuction;if($('#freeContract'))$('#freeContract').onclick=()=>setContract(chooseContract(game,position));if($('#fourthree'))$('#fourthree').onclick=()=>setContract({type:'FOUR_THREE',processor:position})}
async function confirmAuction(){if(!selectedAuction)return;await sendOrApply({type:'AUCTION',action:selectedAuction});selectedAuction=null}
async function setContract(c){await sendOrApply({type:'CONTRACT',contract:c})}
async function confirmPlay(){if(!selected)return;await sendOrApply({type:'PLAY',cardId:selected});selected=null}
async function sendOrApply(action){if(role==='client'){await api('/api/action',{clientId,position,action});return}applyAction(position,action)}
function applyAction(p,a){try{if(a.type==='PLAY'){const r=playCard(game,p,a.cardId);selected=null;if(r.trickComplete){game.tableTrick=(game.wonTricks.at(-1)?.cards||[]).map(x=>({...x,card:{...x.card}}));save();pushViews();renderGame();setTimeout(()=>{game.tableTrick=[];if(r.handComplete){finalizeHand(game);save();if(game.status==='COMPLETED'){finishGame();return}}save();pushViews();renderGame();runTurn()},5000);return}save();pushViews();renderGame();runTurn();return}else if(a.type==='AUCTION'){applyBid(game.auction,p,a.action);const active=game.auction.active;if(active.length===0){game.turn=game.beneficiary}else if(active.length===1){game.turn=game.beneficiary}else{let n=nextPlayer(p);while(!active.includes(n))n=nextPlayer(n);game.turn=n}}else if(a.type==='CONTRACT'){game.contract=a.contract;game.mode=a.contract.type==='NULL'?'NULL':'POSITIVE';game.auction.finished=true;if(a.contract.type==='FOUR_THREE'){game.trickCounts=[3,3,3,3];game.trickCounts[game.beneficiary]=4;finalizeHand(game);save();pushViews();renderGame();runTurn();return}if(a.contract.type==='NULL')game.turn=nextPlayer(a.contract.processor);else game.turn=a.contract.selfLead?a.contract.processor:randomOther(a.contract.processor)}save();pushViews();renderGame();runTurn()}catch(e){toast(e.message)}}
function randomOther(p){const a=[0,1,2,3].filter(x=>x!==p);return a[Math.floor(Math.random()*a.length)]}
function handleRemote(msg){const p=game.players.find(x=>x.id===msg.clientId)?.position;if(p===undefined)return;applyAction(p,msg.action)}
function runTurn(){clearInterval(timer);if(!game||game.status!=='ACTIVE')return;const p=game.turn;if(game.players[p].bot){setTimeout(()=>botAct(p),20);return}seconds=30;timer=setInterval(()=>{seconds--;const el=$('#timer');if(el)el.textContent=seconds;if(seconds<=0){clearInterval(timer);if(p===position){if(game.mode==='AUCTION'){if(selectedAuction)confirmAuction();else if(role==='master')botFallbackHuman(p);else api('/api/action',{clientId,position,action:{type:'TIMEOUT'}})}else{if(selected)confirmPlay();else if(role==='master')applyAction(p,{type:'PLAY',cardId:chooseCard(game,p).id});else api('/api/action',{clientId,position,action:{type:'TIMEOUT'}})}}}},1000)}
function botFallbackHuman(p){if(game.mode==='AUCTION'){const a=chooseBid(game,p);applyAction(p,{type:'AUCTION',action:a})}else applyAction(p,{type:'PLAY',cardId:chooseCard(game,p).id})}
function botAct(p){if(game.mode==='AUCTION'){if(p===game.beneficiary&&game.auction.active.length<=1){setContract(chooseContract(game,p));return}applyAction(p,{type:'AUCTION',action:chooseBid(game,p)})}else applyAction(p,{type:'PLAY',cardId:chooseCard(game,p).id})}
async function finishGame(){clearInterval(timer);const conv=conversionPoints(game.totals);const record={id:game.id,date:new Date().toISOString(),players:game.players.map(x=>x.nickname),handScores:game.handScores,totals:game.totals,conversion:conv,status:'COMPLETED'};const h=JSON.parse(localStorage.kingHistory||'[]');if(!h.some(x=>x.id===record.id))h.push(record);localStorage.kingHistory=JSON.stringify(h);localStorage.removeItem('activeKing');if(!session?.offline)await api('/api/session/complete',{clientId});app.innerHTML=`<div class="shell"><div class="panel home stack"><h2>Partida concluída</h2>${game.players.map((p,i)=>`<div>${p.nickname}: <b>${game.totals[i]}</b> · conversão ${conv[i]}</div>`).join('')}<button class="btn primary" id="home">Início</button></div></div>`;$('#home').onclick=home}
function renderClientWaiting(){app.innerHTML=`<div class="shell"><div class="panel home"><h2>Partida iniciada</h2><p>A aguardar estado do master…</p></div></div>`}
function renderSuspended(){app.innerHTML=`<div class="shell"><div class="panel home"><h2>Partida suspensa</h2><p>A aguardar o anfitrião.</p><p>Limite de recuperação: 60 minutos.</p></div></div>`}
function renderWaiting(){app.innerHTML=`<div class="shell"><div class="panel home stack"><h2>Existe uma partida em curso</h2><p>Aguarde que termine para poder jogar.</p><button class="btn primary" id="wait">Aguardar próxima partida</button><button class="btn secondary" id="back">Voltar</button></div></div>`;$('#wait').onclick=async()=>{try{getNick();const r=await api('/api/queue/join',{clientId,nickname});app.innerHTML=`<div class="shell"><div class="panel home"><h2>Em espera</h2><p>Posição na fila: ${r.position}</p><button class="btn secondary" id="leaveq">Sair da fila</button></div></div>`;$('#leaveq').onclick=async()=>{await api('/api/queue/leave',{clientId});home()}}catch(e){toast(e.message)}};$('#back').onclick=home}
function showHistory(){const h=JSON.parse(localStorage.kingHistory||'[]');app.innerHTML=`<div class="shell"><div class="panel stack"><h2>Histórico deste dispositivo</h2>${h.length?h.slice().reverse().map(x=>`<div><b>${new Date(x.date).toLocaleString('pt-PT')}</b> — ${x.players.map((p,i)=>`${p}: ${x.totals[i]}`).join(' · ')}</div>`).join(''):'Sem partidas concluídas.'}<button class="btn secondary" id="back">Voltar</button></div></div>`;$('#back').onclick=home}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
const recovered=localStorage.activeKing?JSON.parse(localStorage.activeKing):null;if(recovered&&Date.now()-recovered.savedAt<60*60*1000){game=recovered.game;session=recovered.session;role='master';position=0;renderGame();runTurn()}else home();